# Generated by Django 3.2.4 on 2022-01-14 03:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpawRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_id', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('ogc_fid', models.IntegerField(blank=True, null=True)),
                ('office', models.CharField(blank=True, max_length=64, null=True)),
                ('hectares', models.FloatField(blank=True, null=True)),
                ('md5_rowhash', models.CharField(blank=True, max_length=64, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4283)),
            ],
        ),
    ]
