# Generated by Django 3.2.4 on 2022-01-17 09:41

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('srid', models.IntegerField(blank=True, null=True)),
                ('geojson', django.contrib.postgres.fields.jsonb.JSONField(db_index=True, verbose_name='Layer GeoJSON')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_id', models.CharField(max_length=64)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(db_index=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4283)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='qml.layer')),
            ],
        ),
    ]
