# Generated by Django 3.2.4 on 2022-01-18 13:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qml', '0006_auto_20220118_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('geojson', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Layer GeoJSON')),
                ('version', models.IntegerField(editable=False)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layerhistory_features', to='qml.layer')),
            ],
        ),
    ]
