# Generated by Django 3.2.4 on 2022-01-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qml', '0008_alter_layerhistory_layer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('name', 'type')},
        ),
    ]
