# Generated by Django 3.2.4 on 2022-01-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qml', '0010_alter_layerhistory_layer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='layerhistory',
            unique_together={('version', 'layer')},
        ),
    ]
