# Generated by Django 3.2.4 on 2022-01-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qml', '0012_layer_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='attributes',
            new_name='properties',
        ),
    ]
